[package]
name = "cranelift-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
cranelift = "0.119.0"
cranelift-module = "0.119.0"
cranelift-native = "0.119.0"
cranelift-object = "0.119.0"
memmap2 = "0.9.5"

