#include <stdio.h>
#include <stdint.h> // int64_t

// Declare the external function from tempo.o (generated by Rust/Cranelift)
// Signature: main = |a| { add(2, a) }
// Expected C signature: int64_t tempo_entry(int64_t a);
extern int64_t tempo_entry(int64_t arg);

// Function to be called by Cranelift-generated code (e.g., 'add')
int64_t add(int64_t a, int64_t b) {
    printf("C: add(%lld, %lld) called\n", (long long)a, (long long)b);
    return a + b;
}

// The get_two_from_c function is no longer called by the current Cranelift code.
// It can be kept or removed. For now, let's keep it to avoid breaking old states if any.
int64_t get_two_from_c() {
    printf("C: get_two_from_c() called (Note: This function might be unused by current tempo.o)\n");
    return 2;
}

int main() {
    int64_t input_val = 10; // This will be 'a' in 'main = |a| { add(2, a) }'
    int64_t result_val;

    printf("C: Calling Cranelift-generated function tempo_entry with %lld\n", (long long)input_val);
    result_val = tempo_entry(input_val); // Call the function
                                         // Expected: add(2, 10) = 12
    printf("C: Received result from tempo_entry: %lld\n", (long long)result_val);
    return 0;
}
